date.timezone = Asia/Shanghai

memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 120

opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

session.save_handler = redis
session.save_path = "tcp://redis:6379?database=1&prefix=acg_sess:"
